name: Pulmi Destroy

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    env:
      PULUMI_WORK_DIR: ./.pulumi/shared/
      PULUMI_STATE_CONTAINER_NAME: sharedstatestore
      PULUMI_STACK_NAME: example-shared
      PULUMI_STATE_STORAGE_ACCOUNT_NAME: uksshrpulstatesa01
      PULUMI_STACK_SECRETS_AZURE_KEY_VAULT: ukshrpulstatekv01
      PULUMI_STACK_SECRETS_AZURE_KEY_VAULT_KEY: PulumiSharedSecrets

    steps:
      - uses: actions/checkout@v4
        name: Checkout source

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Display Azure contents
        run: |
          az account show -o table
          az storage account list -o table
          az storage blob list --container-name ${{ env.PULUMI_STATE_CONTAINER_NAME }} --account-name ${{ env.PULUMI_STATE_STORAGE_ACCOUNT_NAME }} --auth-mode login -o table
          az keyvault key list --vault-name ${{ env.PULUMI_STACK_SECRETS_AZURE_KEY_VAULT }} -o table

      - name: Run NPM install for pulumi def
        run: |
          cd ./.pulumi/shared
          npm install
          pulumi login --cloud-url azblob://${{ env.PULUMI_STATE_CONTAINER_NAME }}?storage_account=${{ env.PULUMI_STATE_STORAGE_ACCOUNT_NAME }} -v=3
          pulumi stack select ${{ env.PULUMI_STACK_NAME }} -c
          pulumi stack change-secrets-provider "azurekeyvault://${{ env.PULUMI_STACK_SECRETS_AZURE_KEY_VAULT }}.vault.azure.net/keys/${{ env.PULUMI_STACK_SECRETS_AZURE_KEY_VAULT_KEY }}"
          pulumi destroy --yes
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_KEYVAULT_AUTH_VIA_CLI: "true"
