name: Pulmi Deploy

on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - uses: pulumi/actions@v4
        with:
          command: up
          cloud-url: azblob://sharedstatestore
          stack-name: example-shared
        env:
          AZURE_STORAGE_ACCOUNT: uksshrpulstatesa01
