name: Pulmi Deploy

on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Configure pulumi creds
        run: |
          cd ./.pulumi/shared/
      #       pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }}
      #       pulumi config set azure:clientSecret  ${{ secrets.AZURE_CLIENT_SECRET }} --secret
      #       pulumi config set azure:tenantId  ${{ secrets.AZURE_TENANT_ID }}
      #       pulumi config set azure:subscriptionId  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Pulumi
        run: pulumi login azblob://sharedstatestore?storage_account=uksshrpulstatesa01
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - uses: pulumi/actions@v4
        with:
          command: up
          cloud-url: azblob://sharedstatestore
          stack-name: example-shared
        env:
          AZURE_STORAGE_ACCOUNT: uksshrpulstatesa01
