name: Pulmi Deploy

on: [push, workflow_dispatch]

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pulumi/actions@v4
        with:
          command: up
          cloud-url: azblob://my-blob-name-and-path
          stack-name: example-shared
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
